name: SKIMA watcher

on:
  schedule:
    # UTC で 5 分毎。日本時間 (UTC+9) に換算不要＝GitHub では常に UTC
    - cron: "*/15 * * * *"
  workflow_dispatch:      # 手動トリガも付けると便利

jobs:
  run:
    runs-on: ubuntu-latest
    # 同時実行を避ける◆
    concurrency:
      group: skima-watch
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests beautifulsoup4

      # shelve の DB をキャッシュ◆
      - uses: actions/cache@v4
        with:
          path: .cache
          key: skima-watch-cache

      - run: python skima_watch.py
        env:
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
