name: Purge all GitHub-Actions caches

on:
  # 「Run workflow」ボタンから手動実行
  workflow_dispatch:

permissions:
  actions: write          # ← cache 削除には write 権限が必須
  contents: read

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
    - name: Delete every cache in the repo
      uses: actions/github-script@v7
      with:
        # ${{ github.token }} はデフォルトで使用可
        script: |
          const owner = context.repo.owner;
          const repo  = context.repo.repo;
          let page    = 1, deleted = 0;

          for (;;) {
            // ① 100件ずつキャッシュ一覧を取得（最大1,000件まで繰り返し）
            const { data } = await github.request(
              'GET /repos/{owner}/{repo}/actions/caches',
              { owner, repo, per_page: 100, page }
            );

            if (data.actions_caches.length === 0) break;

            for (const c of data.actions_caches) {
              await github.request(
                'DELETE /repos/{owner}/{repo}/actions/caches/{cache_id}',
                { owner, repo, cache_id: c.id }
              );
              core.info(`✔ deleted ${c.key}`);
              deleted++;
            }
            page++;
          }

          core.summary.addHeading('Cache purge done');
          core.summary.addRaw(`Total deleted: **${deleted}**`).write();
